services:
  - type: web
    name: seashore-cedar
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.bundle.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: CONTACT_FORM_RECIPIENT_EMAIL
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: VITE_RECAPTCHA_SITE_KEY
        sync: false
      - key: VITE_ADMIN_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        sync: false
